# Action setup:
#
# Copy this action to .github/workflows
#
# Add GH_TOKEN, which is Personal Access Token (PAT), to secrets or rename GH_TOKEN in this code to an already existing token
#
# Add to .gitignore a comment before line that ignores result of the build with the following postfix:
#   (next line will be removed by pre-release-branch-update GitHub action to be included in dist branch)
#
# Copy PRE-RELEASE.md rom this project

name: Pre-Release branch update
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install dependencies
        run: npm ci
        shell: bash
      - name: Remove build result from .gitignore
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: ".gitignore"
          find: "#.*\\(next line will be removed by build-typescript GitHub action to be included in dist branch\\)\\n.*\\n"
          replace: "###\\n"
      - name: Build typescript project
        run: npm run build
        shell: bash
      - name: Commit files to pre-release branch
        run: |
          git config --local user.email "azorkaltsev@yandex-team.ru"
          git config --local user.name "pre-release-to-branch[action]"
          git add .
          git commit -a -m "Typescript build"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: "pre-release"
