on:
  push:
    branches: [main]

name: release

jobs:
  release:
    if: github.repository == 'ydb-platform/ydb-nodejs-sdk'
    runs-on: ubuntu-latest
    steps:
      - uses: gravity-ui/release-action@v1
        with:
          github-token: ${{ secrets.YDB_PLATFORM_BOT_TOKEN_REPO }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN }}
